# Generated by Django 4.0.4 on 2022-11-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de material')),
                ('nombreMaterial', models.CharField(max_length=50, verbose_name='Nombre de material')),
                ('descripcionMaterial', models.CharField(max_length=50, verbose_name='Descripcion de material')),
                ('stock', models.IntegerField(verbose_name='Stock de material')),
            ],
        ),
    ]
