# Generated by Django 4.0.4 on 2022-12-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('idInstructor', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de instructor')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre de instructor')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido de instructor')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo de instructor')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de instructor')),
                ('rut', models.CharField(max_length=50, verbose_name='rut de instructor')),
                ('estado', models.CharField(max_length=50, verbose_name='estado de instructor')),
            ],
        ),
        migrations.CreateModel(
            name='PostulacionInstr',
            fields=[
                ('idPostulacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de postulacion')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre de postulante')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido de postulante')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo de postulante')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de postulante')),
                ('rut', models.CharField(max_length=50, verbose_name='rut de postulante')),
                ('estado', models.CharField(max_length=50, verbose_name='estado de postulante')),
            ],
        ),
    ]
